export const skills: Record<string, string[]> = {
  "AI & Machine Learning": [
    "Python", "TensorFlow", "Scikit-learn", "Deep Learning", "CNN", "RNN",
    "LSTM", "NLP", "BERT", "BART", "Word2Vec", "LDA/NMF", "Transfer Learning",
    "Computer Vision", "OpenCV", "Forecasting", "Predictive Modelling",
  ],
  "Cloud & Infrastructure": [
    "Microsoft Azure", "Azure VM Management", "Disk Migration", "Log Management",
    "Bash Scripting", "Git", "GitHub", "AWS (learning)",
  ],
  "Web & App Development": [
    "Firebase", "CMS Integration", "Multi-tenant SSR", "PWA Development",
    "REST APIs", "FastAPI", "Gmail API", "HTML", "CSS",
  ],
  "Data & Analysis": [
    "NumPy", "Pandas", "Data Pipelines", "Data Visualisation", "EDA", "SQL", "MySQL",
  ],
  "Languages": ["Python", "SQL", "Bash", "C", "C++", "C#", "HTML", "CSS"],
  "AI Agent & LLM Tooling": [
    "LLM Evaluation", "Prompt Engineering", "Agent Testing", "Claude", "AI Feature Scoping",
  ],
  "Hardware & Embedded Systems": [
    "Arduino", "Raspberry Pi", "IoT", "PCB Handling", "Network Infrastructure", "CCTV Systems",
  ],
  "Tools & Platforms": [
    "VS Code", "Visual Studio", "MS Office", "Agile / Scrum", "Technical Documentation",
  ],
};

export const skillCategories = [
  { name: "AI & ML",    color: "#14b8a6", key: "AI & Machine Learning" },
  { name: "Cloud",      color: "#0ea5e9", key: "Cloud & Infrastructure" },
  { name: "Web & App",  color: "#a855f7", key: "Web & App Development" },
  { name: "Data",       color: "#f59e0b", key: "Data & Analysis" },
  { name: "Languages",  color: "#22c55e", key: "Languages" },
  { name: "LLM / AI",   color: "#ec4899", key: "AI Agent & LLM Tooling" },
  { name: "IoT",        color: "#ef4444", key: "Hardware & Embedded Systems" },
  { name: "Tools",      color: "#94a3b8", key: "Tools & Platforms" },
];

export const skillNodes = [
  { id: "python",      label: "Python",           category: "AI & ML",   size: 1.5 },
  { id: "tensorflow",  label: "TensorFlow",        category: "AI & ML" },
  { id: "sklearn",     label: "Scikit-learn",      category: "AI & ML" },
  { id: "nlp",         label: "NLP",               category: "AI & ML",   size: 1.2 },
  { id: "bert",        label: "BERT",              category: "AI & ML" },
  { id: "bart",        label: "BART",              category: "AI & ML" },
  { id: "cv",          label: "Computer Vision",   category: "AI & ML",   size: 1.2 },
  { id: "cnn",         label: "CNN",               category: "AI & ML" },
  { id: "lstm",        label: "LSTM",              category: "AI & ML" },
  { id: "transfer",    label: "Transfer Learning", category: "AI & ML" },
  { id: "word2vec",    label: "Word2Vec",           category: "AI & ML" },
  { id: "azure",       label: "Azure",             category: "Cloud",     size: 1.3 },
  { id: "bash",        label: "Bash",              category: "Cloud" },
  { id: "git",         label: "Git / GitHub",      category: "Cloud" },
  { id: "aws",         label: "AWS",               category: "Cloud" },
  { id: "firebase",    label: "Firebase",          category: "Web & App", size: 1.2 },
  { id: "fastapi",     label: "FastAPI",           category: "Web & App" },
  { id: "pwa",         label: "PWA",               category: "Web & App" },
  { id: "rest",        label: "REST APIs",         category: "Web & App" },
  { id: "cms",         label: "CMS",               category: "Web & App" },
  { id: "numpy",       label: "NumPy",             category: "Data" },
  { id: "pandas",      label: "Pandas",            category: "Data" },
  { id: "sql",         label: "SQL",               category: "Data",      size: 1.2 },
  { id: "dataviz",     label: "Data Viz",          category: "Data" },
  { id: "cpp",         label: "C / C++",           category: "Languages" },
  { id: "csharp",      label: "C#",                category: "Languages" },
  { id: "llm",         label: "LLM Eval",          category: "LLM / AI" },
  { id: "prompt",      label: "Prompt Eng.",       category: "LLM / AI" },
  { id: "claude",      label: "Claude",            category: "LLM / AI" },
  { id: "arduino",     label: "Arduino",           category: "IoT" },
  { id: "raspberrypi", label: "Raspberry Pi",      category: "IoT" },
  { id: "iot",         label: "IoT",               category: "IoT",       size: 1.2 },
  { id: "agile",       label: "Agile / Scrum",     category: "Tools" },
  { id: "vscode",      label: "VS Code",           category: "Tools" },
];

export const skillLinks = [
  { source: "python",     target: "tensorflow" },
  { source: "python",     target: "sklearn" },
  { source: "python",     target: "nlp" },
  { source: "python",     target: "cv" },
  { source: "python",     target: "numpy" },
  { source: "python",     target: "pandas" },
  { source: "python",     target: "fastapi" },
  { source: "python",     target: "llm" },
  { source: "nlp",        target: "bert" },
  { source: "nlp",        target: "bart" },
  { source: "nlp",        target: "word2vec" },
  { source: "tensorflow", target: "cnn" },
  { source: "tensorflow", target: "lstm" },
  { source: "tensorflow", target: "transfer" },
  { source: "cv",         target: "cnn" },
  { source: "azure",      target: "bash" },
  { source: "azure",      target: "git" },
  { source: "firebase",   target: "cms" },
  { source: "firebase",   target: "pwa" },
  { source: "fastapi",    target: "rest" },
  { source: "rest",       target: "firebase" },
  { source: "numpy",      target: "pandas" },
  { source: "pandas",     target: "dataviz" },
  { source: "sql",        target: "pandas" },
  { source: "arduino",    target: "iot" },
  { source: "raspberrypi", target: "iot" },
  { source: "raspberrypi", target: "sql" },
  { source: "llm",        target: "prompt" },
  { source: "llm",        target: "claude" },
  { source: "bash",       target: "git" },
];

export const projects = [
  {
    title: "Personal Website",
    status: "Deployed",
    statusColor: "green",
    description:
      "A personal portfolio and professional presence website, designed and built independently from scratch. Demonstrates end-to-end ownership of a web project — from design decisions to live deployment.",
    tags: ["Web Development", "Frontend", "Deployment"],
    liveUrl: null as string | null,
    liveLabel: "Live" as string | null,
    codeUrl: null as string | null,
    codeLabel: "Private — IP Protected" as string | null,
    highlight: null as string | null,
  },
  {
    title: "PWA Web Application",
    status: "Ready to Deploy",
    statusColor: "blue",
    description:
      "A full Progressive Web App built for cross-platform deployment — bypassing the need for separate Android and iOS native builds. Independently designed and developed, production-ready.",
    tags: ["PWA", "Full-Stack", "Web App", "Cross-platform"],
    liveUrl: null,
    liveLabel: "Demo available on request",
    codeUrl: null,
    codeLabel: "Private — IP Protected",
    highlight: null,
  },
  {
    title: "Python Invoicing App for ABN Workers",
    status: "In Development",
    statusColor: "amber",
    description:
      "An offline-first invoicing tool supporting multiple ABN worker accounts with different employers, pay rates, and worksites. Automates invoice generation and delivery via Gmail API, with Fernet-encrypted local data storage.",
    tags: ["Python", "Gmail API", "Automation", "Encryption", "python-docx"],
    liveUrl: null,
    liveLabel: null,
    codeUrl: "https://github.com/bibekalce",
    codeLabel: "GitHub",
    highlight: "Currently being upgraded to a PWA for cross-platform access.",
  },
  {
    title: "Enhancing Recommender System using Deep Learning & NLP",
    status: "University Project",
    statusColor: "slate",
    description:
      "Applied NLP techniques (Topic Modelling, Sentiment Analysis, Word2Vec) combined with CNN via TensorFlow to build an explainable recommender system — translating raw user reviews into structured user and product profiles.",
    tags: ["Python", "TensorFlow", "NLP", "CNN", "Deep Learning", "Word2Vec", "Agile"],
    liveUrl: null,
    liveLabel: null,
    codeUrl: "https://github.com/bibekalce/Recommendor-system-Using-NLP-and-CNN/",
    codeLabel: "GitHub",
    highlight: null,
  },
  {
    title: "Closed-Domain Question Answering System (CORD-19)",
    status: "University Project",
    statusColor: "slate",
    description:
      "Built a factoid QA system over 10,000 COVID-19 research documents, using BART for summarisation and BERT SQuAD 2.0 for precise answer extraction from a pre-built knowledge corpus.",
    tags: ["Python", "BERT", "BART", "NLP", "Information Retrieval"],
    liveUrl: null,
    liveLabel: null,
    codeUrl: "https://github.com/bibekalce/Closed-Domain-Factoid-Question-Answering-System-on-theCORD-19-Dataset",
    codeLabel: "GitHub",
    highlight: null,
  },
  {
    title: "Animal Classification using Transfer Learning",
    status: "University Project",
    statusColor: "slate",
    description:
      "Deep learning model classifying 6,270 animal images across 151 categories using MobileNetV2 and EfficientNet-B4. Achieved 98.28% Top-5 accuracy on the test set.",
    tags: ["Python", "Transfer Learning", "CNN", "MobileNetV2", "EfficientNet", "Computer Vision"],
    liveUrl: null,
    liveLabel: null,
    codeUrl: "https://github.com/bibekalce/Animal-Classification-using-Transfer-Learning",
    codeLabel: "GitHub",
    highlight: null,
  },
  {
    title: "Smart Rooftop Farming System",
    status: "Deployed",
    statusColor: "green",
    description:
      "Arduino and Raspberry Pi-based smart greenhouse system regulating lighting, irrigation, temperature, and CO₂ in real time. Built under Nepal Communitere's business incubation program with SQL data logging and a custom web interface.",
    tags: ["IoT", "Arduino", "Raspberry Pi", "SQL", "Embedded Systems", "Web Interface"],
    liveUrl: null,
    liveLabel: "Hardware project — no public repo",
    codeUrl: null,
    codeLabel: null,
    highlight: null,
  },
  {
    title: "Feature Matching & Image Retrieval",
    status: "University Project",
    statusColor: "slate",
    description:
      "Computer vision project implementing image matching and retrieval using OpenCV, with RANSAC-based accuracy improvements for robust feature detection.",
    tags: ["Python", "OpenCV", "Computer Vision", "RANSAC"],
    liveUrl: "https://colab.research.google.com/drive/1z9lHD802zmPaz-8vR4a0moS_H_CGKDFa",
    liveLabel: "View in Colab",
    codeUrl: null,
    codeLabel: null,
    highlight: null,
  },
];

export const experience = {
  ict: [
    {
      title: "ICT Intern",
      company: "Jaba Pty Ltd",
      location: "Adelaide, SA",
      dates: "January 2026 – April 2026",
      note: "Professional Year Program (ICT) · Academy IT",
      tags: ["Full-Stack", "Azure", "Firebase", "AI Agent Tooling", "CMS", "Bash"],
      bullets: [
        "Designed and prototyped a multi-tenant server-side rendering system to improve web development scalability for client sites.",
        "Integrated a CMS with Firebase, managed database structure, and set up client-facing systems in a live production environment.",
        "Completed Azure disk migration from unmanaged to managed disks, improving cloud resource management and system reliability.",
        "Resolved a large-scale Azure log storage issue and automated ongoing management with a custom Bash script.",
        "Researched, evaluated, and compared AI agent tools and LLM models for practical business use, including prompt testing and performance assessment.",
        "Delivered technical presentations to clients on proposed AI features and system designs.",
      ],
    },
    {
      title: "IT Support",
      company: "Ultra Tech Solar Pvt Ltd",
      location: "Kathmandu, Nepal",
      dates: "November 2017 – April 2018",
      note: null as string | null,
      tags: ["IT Support", "Networking", "CCTV", "Hardware", "Infrastructure"],
      bullets: [
        "Resolved internet connectivity issues, managed router/modem troubleshooting, and coordinated with ISPs for stable network performance.",
        "Installed and maintained a 32-channel DVR CCTV system with 16+ cameras for onsite and remote surveillance.",
        "Handled full office IT setup during relocations — network cabling, PC deployment, and hardware installation.",
        "Provided ongoing technical support across all office IT systems, ensuring minimal downtime.",
      ],
    },
  ],
  other: [
    {
      title: "Assistant Store Manager",
      company: "Liquorland",
      location: "Adelaide, SA",
      dates: "February 2023 – Present",
      note: "Held concurrently with Master's degree and PY Program",
      bullets: [
        "Managed day-to-day store operations, staff rostering, inventory, and RSA compliance in a fast-paced retail environment.",
        "Progressed from Sales Assistant → Acting Store Manager → Assistant Store Manager over 3 years.",
      ],
    },
  ],
};

export const nonTechnicalSkills = [
  { name: "Problem Solving",         desc: "Breaking complex problems into clear, workable solutions" },
  { name: "Technical Communication", desc: "Explaining AI systems and technical designs to non-technical clients" },
  { name: "Client Presentations",    desc: "Delivered technical and AI feature presentations at Jaba Pty Ltd" },
  { name: "Research & Analysis",     desc: "Academic and applied research across ML, NLP, and embedded systems" },
  { name: "Team Collaboration",      desc: "Cross-functional teamwork in academic and professional settings" },
  { name: "Self-directed Learning",  desc: "Built and deployed independent web projects alongside full-time study" },
  { name: "Agile / Scrum",           desc: "Applied in university team projects and professional work" },
  { name: "Attention to Detail",     desc: "Precision in code, documentation, and system design" },
];

export const education = [
  {
    qualification: "Professional Year Program (ICT)",
    institution: "Academy IT, Adelaide",
    period: "Completed April 2026",
    color: "#14b8a6",
    notes: ["ACS-accredited", "12-week industry internship", "Australian ICT workplace readiness"],
  },
  {
    qualification: "Master of Artificial Intelligence and Machine Learning",
    institution: "The University of Adelaide",
    period: "April 2022 – April 2024",
    color: "#0ea5e9",
    notes: ["Deep Learning", "NLP", "Computer Vision", "Transfer Learning", "Forecasting", "Data Pipelines"],
  },
  {
    qualification: "Bachelor of Electronics and Communication Engineering",
    institution: "Himalaya College of Engineering (Tribhuvan University), Nepal",
    period: "November 2014 – September 2018",
    color: "#a855f7",
    notes: ["Embedded Systems", "IoT", "Microcontrollers", "Communications", "Circuit Design"],
  },
];
